/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PostIdeasRouteImport } from './routes/post-ideas'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as CreateContentRouteImport } from './routes/create-content'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as SettingsTargetAudienceRouteImport } from './routes/settings.target-audience'
import { Route as OperatorInboxRouteImport } from './routes/operator.inbox'
import { Route as OperatorCalendarRouteImport } from './routes/operator.calendar'
import { Route as ApiIdeaChatRouteImport } from './routes/api/idea-chat'
import { Route as OperatorPostsIndexRouteImport } from './routes/operator.posts.index'
import { Route as OperatorClientsIndexRouteImport } from './routes/operator.clients.index'
import { Route as OperatorPostsPostIdRouteImport } from './routes/operator.posts.$postId'
import { Route as OperatorClientsClientIdRouteImport } from './routes/operator.clients.$clientId'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdeasRoute = PostIdeasRouteImport.update({
  id: '/post-ideas',
  path: '/post-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateContentRoute = CreateContentRouteImport.update({
  id: '/create-content',
  path: '/create-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const SettingsTargetAudienceRoute = SettingsTargetAudienceRouteImport.update({
  id: '/settings/target-audience',
  path: '/settings/target-audience',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorInboxRoute = OperatorInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorCalendarRoute = OperatorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => OperatorRoute,
} as any)
const ApiIdeaChatRoute = ApiIdeaChatRouteImport.update({
  id: '/api/idea-chat',
  path: '/api/idea-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorPostsIndexRoute = OperatorPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorClientsIndexRoute = OperatorClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPostsPostIdRoute = OperatorPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorClientsClientIdRoute = OperatorClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => OperatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/calendar': typeof CalendarRoute
  '/comments': typeof CommentsRoute
  '/content': typeof ContentRoute
  '/create-content': typeof CreateContentRoute
  '/earn': typeof EarnRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/onboarding': typeof OnboardingRoute
  '/operator': typeof OperatorRouteWithChildren
  '/post-ideas': typeof PostIdeasRoute
  '/report': typeof ReportRoute
  '/schedule': typeof ScheduleRoute
  '/trending': typeof TrendingRoute
  '/api/idea-chat': typeof ApiIdeaChatRoute
  '/operator/calendar': typeof OperatorCalendarRoute
  '/operator/inbox': typeof OperatorInboxRoute
  '/settings/target-audience': typeof SettingsTargetAudienceRoute
  '/operator/': typeof OperatorIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/operator/clients/$clientId': typeof OperatorClientsClientIdRoute
  '/operator/posts/$postId': typeof OperatorPostsPostIdRoute
  '/operator/clients/': typeof OperatorClientsIndexRoute
  '/operator/posts/': typeof OperatorPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/calendar': typeof CalendarRoute
  '/comments': typeof CommentsRoute
  '/content': typeof ContentRoute
  '/create-content': typeof CreateContentRoute
  '/earn': typeof EarnRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/onboarding': typeof OnboardingRoute
  '/post-ideas': typeof PostIdeasRoute
  '/report': typeof ReportRoute
  '/schedule': typeof ScheduleRoute
  '/trending': typeof TrendingRoute
  '/api/idea-chat': typeof ApiIdeaChatRoute
  '/operator/calendar': typeof OperatorCalendarRoute
  '/operator/inbox': typeof OperatorInboxRoute
  '/settings/target-audience': typeof SettingsTargetAudienceRoute
  '/operator': typeof OperatorIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/operator/clients/$clientId': typeof OperatorClientsClientIdRoute
  '/operator/posts/$postId': typeof OperatorPostsPostIdRoute
  '/operator/clients': typeof OperatorClientsIndexRoute
  '/operator/posts': typeof OperatorPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/calendar': typeof CalendarRoute
  '/comments': typeof CommentsRoute
  '/content': typeof ContentRoute
  '/create-content': typeof CreateContentRoute
  '/earn': typeof EarnRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/onboarding': typeof OnboardingRoute
  '/operator': typeof OperatorRouteWithChildren
  '/post-ideas': typeof PostIdeasRoute
  '/report': typeof ReportRoute
  '/schedule': typeof ScheduleRoute
  '/trending': typeof TrendingRoute
  '/api/idea-chat': typeof ApiIdeaChatRoute
  '/operator/calendar': typeof OperatorCalendarRoute
  '/operator/inbox': typeof OperatorInboxRoute
  '/settings/target-audience': typeof SettingsTargetAudienceRoute
  '/operator/': typeof OperatorIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/operator/clients/$clientId': typeof OperatorClientsClientIdRoute
  '/operator/posts/$postId': typeof OperatorPostsPostIdRoute
  '/operator/clients/': typeof OperatorClientsIndexRoute
  '/operator/posts/': typeof OperatorPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/brain'
    | '/calendar'
    | '/comments'
    | '/content'
    | '/create-content'
    | '/earn'
    | '/home'
    | '/inbox'
    | '/kanban'
    | '/onboarding'
    | '/operator'
    | '/post-ideas'
    | '/report'
    | '/schedule'
    | '/trending'
    | '/api/idea-chat'
    | '/operator/calendar'
    | '/operator/inbox'
    | '/settings/target-audience'
    | '/operator/'
    | '/settings/'
    | '/operator/clients/$clientId'
    | '/operator/posts/$postId'
    | '/operator/clients/'
    | '/operator/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/brain'
    | '/calendar'
    | '/comments'
    | '/content'
    | '/create-content'
    | '/earn'
    | '/home'
    | '/inbox'
    | '/kanban'
    | '/onboarding'
    | '/post-ideas'
    | '/report'
    | '/schedule'
    | '/trending'
    | '/api/idea-chat'
    | '/operator/calendar'
    | '/operator/inbox'
    | '/settings/target-audience'
    | '/operator'
    | '/settings'
    | '/operator/clients/$clientId'
    | '/operator/posts/$postId'
    | '/operator/clients'
    | '/operator/posts'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/brain'
    | '/calendar'
    | '/comments'
    | '/content'
    | '/create-content'
    | '/earn'
    | '/home'
    | '/inbox'
    | '/kanban'
    | '/onboarding'
    | '/operator'
    | '/post-ideas'
    | '/report'
    | '/schedule'
    | '/trending'
    | '/api/idea-chat'
    | '/operator/calendar'
    | '/operator/inbox'
    | '/settings/target-audience'
    | '/operator/'
    | '/settings/'
    | '/operator/clients/$clientId'
    | '/operator/posts/$postId'
    | '/operator/clients/'
    | '/operator/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BrainRoute: typeof BrainRoute
  CalendarRoute: typeof CalendarRoute
  CommentsRoute: typeof CommentsRoute
  ContentRoute: typeof ContentRoute
  CreateContentRoute: typeof CreateContentRoute
  EarnRoute: typeof EarnRoute
  HomeRoute: typeof HomeRoute
  InboxRoute: typeof InboxRoute
  KanbanRoute: typeof KanbanRoute
  OnboardingRoute: typeof OnboardingRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  PostIdeasRoute: typeof PostIdeasRoute
  ReportRoute: typeof ReportRoute
  ScheduleRoute: typeof ScheduleRoute
  TrendingRoute: typeof TrendingRoute
  ApiIdeaChatRoute: typeof ApiIdeaChatRoute
  SettingsTargetAudienceRoute: typeof SettingsTargetAudienceRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ideas': {
      id: '/post-ideas'
      path: '/post-ideas'
      fullPath: '/post-ideas'
      preLoaderRoute: typeof PostIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-content': {
      id: '/create-content'
      path: '/create-content'
      fullPath: '/create-content'
      preLoaderRoute: typeof CreateContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/settings/target-audience': {
      id: '/settings/target-audience'
      path: '/settings/target-audience'
      fullPath: '/settings/target-audience'
      preLoaderRoute: typeof SettingsTargetAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/inbox': {
      id: '/operator/inbox'
      path: '/inbox'
      fullPath: '/operator/inbox'
      preLoaderRoute: typeof OperatorInboxRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/calendar': {
      id: '/operator/calendar'
      path: '/calendar'
      fullPath: '/operator/calendar'
      preLoaderRoute: typeof OperatorCalendarRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/api/idea-chat': {
      id: '/api/idea-chat'
      path: '/api/idea-chat'
      fullPath: '/api/idea-chat'
      preLoaderRoute: typeof ApiIdeaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/posts/': {
      id: '/operator/posts/'
      path: '/posts'
      fullPath: '/operator/posts/'
      preLoaderRoute: typeof OperatorPostsIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/clients/': {
      id: '/operator/clients/'
      path: '/clients'
      fullPath: '/operator/clients/'
      preLoaderRoute: typeof OperatorClientsIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/posts/$postId': {
      id: '/operator/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/operator/posts/$postId'
      preLoaderRoute: typeof OperatorPostsPostIdRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/clients/$clientId': {
      id: '/operator/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/operator/clients/$clientId'
      preLoaderRoute: typeof OperatorClientsClientIdRouteImport
      parentRoute: typeof OperatorRoute
    }
  }
}

interface OperatorRouteChildren {
  OperatorCalendarRoute: typeof OperatorCalendarRoute
  OperatorInboxRoute: typeof OperatorInboxRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  OperatorClientsClientIdRoute: typeof OperatorClientsClientIdRoute
  OperatorPostsPostIdRoute: typeof OperatorPostsPostIdRoute
  OperatorClientsIndexRoute: typeof OperatorClientsIndexRoute
  OperatorPostsIndexRoute: typeof OperatorPostsIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorCalendarRoute: OperatorCalendarRoute,
  OperatorInboxRoute: OperatorInboxRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  OperatorClientsClientIdRoute: OperatorClientsClientIdRoute,
  OperatorPostsPostIdRoute: OperatorPostsPostIdRoute,
  OperatorClientsIndexRoute: OperatorClientsIndexRoute,
  OperatorPostsIndexRoute: OperatorPostsIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  BrainRoute: BrainRoute,
  CalendarRoute: CalendarRoute,
  CommentsRoute: CommentsRoute,
  ContentRoute: ContentRoute,
  CreateContentRoute: CreateContentRoute,
  EarnRoute: EarnRoute,
  HomeRoute: HomeRoute,
  InboxRoute: InboxRoute,
  KanbanRoute: KanbanRoute,
  OnboardingRoute: OnboardingRoute,
  OperatorRoute: OperatorRouteWithChildren,
  PostIdeasRoute: PostIdeasRoute,
  ReportRoute: ReportRoute,
  ScheduleRoute: ScheduleRoute,
  TrendingRoute: TrendingRoute,
  ApiIdeaChatRoute: ApiIdeaChatRoute,
  SettingsTargetAudienceRoute: SettingsTargetAudienceRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
