/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PostIdeasRouteImport } from './routes/post-ideas'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as CreateContentRouteImport } from './routes/create-content'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as SettingsTargetAudienceRouteImport } from './routes/settings.target-audience'
import { Route as OpsReportsRouteImport } from './routes/ops.reports'
import { Route as OpsInboxRouteImport } from './routes/ops.inbox'
import { Route as OpsCalendarRouteImport } from './routes/ops.calendar'
import { Route as ApiIdeaChatRouteImport } from './routes/api/idea-chat'
import { Route as OpsPostsIndexRouteImport } from './routes/ops.posts.index'
import { Route as OpsClientsIndexRouteImport } from './routes/ops.clients.index'
import { Route as OpsSessionWorkspaceIdRouteImport } from './routes/ops.session.$workspaceId'
import { Route as OpsPostsPostIdRouteImport } from './routes/ops.posts.$postId'
import { Route as OpsClientsClientIdRouteImport } from './routes/ops.clients.$clientId'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdeasRoute = PostIdeasRouteImport.update({
  id: '/post-ideas',
  path: '/post-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateContentRoute = CreateContentRouteImport.update({
  id: '/create-content',
  path: '/create-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const SettingsTargetAudienceRoute = SettingsTargetAudienceRouteImport.update({
  id: '/settings/target-audience',
  path: '/settings/target-audience',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsReportsRoute = OpsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInboxRoute = OpsInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => OpsRoute,
} as any)
const OpsCalendarRoute = OpsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => OpsRoute,
} as any)
const ApiIdeaChatRoute = ApiIdeaChatRouteImport.update({
  id: '/api/idea-chat',
  path: '/api/idea-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsPostsIndexRoute = OpsPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsClientsIndexRoute = OpsClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSessionWorkspaceIdRoute = OpsSessionWorkspaceIdRouteImport.update({
  id: '/session/$workspaceId',
  path: '/session/$workspaceId',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPostsPostIdRoute = OpsPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => OpsRoute,
} as any)
const OpsClientsClientIdRoute = OpsClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => OpsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/calendar': typeof CalendarRoute
  '/comments': typeof CommentsRoute
  '/content': typeof ContentRoute
  '/create-content': typeof CreateContentRoute
  '/earn': typeof EarnRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRouteWithChildren
  '/post-ideas': typeof PostIdeasRoute
  '/report': typeof ReportRoute
  '/schedule': typeof ScheduleRoute
  '/trending': typeof TrendingRoute
  '/api/idea-chat': typeof ApiIdeaChatRoute
  '/ops/calendar': typeof OpsCalendarRoute
  '/ops/inbox': typeof OpsInboxRoute
  '/ops/reports': typeof OpsReportsRoute
  '/settings/target-audience': typeof SettingsTargetAudienceRoute
  '/ops/': typeof OpsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/ops/clients/$clientId': typeof OpsClientsClientIdRoute
  '/ops/posts/$postId': typeof OpsPostsPostIdRoute
  '/ops/session/$workspaceId': typeof OpsSessionWorkspaceIdRoute
  '/ops/clients/': typeof OpsClientsIndexRoute
  '/ops/posts/': typeof OpsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/calendar': typeof CalendarRoute
  '/comments': typeof CommentsRoute
  '/content': typeof ContentRoute
  '/create-content': typeof CreateContentRoute
  '/earn': typeof EarnRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/onboarding': typeof OnboardingRoute
  '/post-ideas': typeof PostIdeasRoute
  '/report': typeof ReportRoute
  '/schedule': typeof ScheduleRoute
  '/trending': typeof TrendingRoute
  '/api/idea-chat': typeof ApiIdeaChatRoute
  '/ops/calendar': typeof OpsCalendarRoute
  '/ops/inbox': typeof OpsInboxRoute
  '/ops/reports': typeof OpsReportsRoute
  '/settings/target-audience': typeof SettingsTargetAudienceRoute
  '/ops': typeof OpsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/ops/clients/$clientId': typeof OpsClientsClientIdRoute
  '/ops/posts/$postId': typeof OpsPostsPostIdRoute
  '/ops/session/$workspaceId': typeof OpsSessionWorkspaceIdRoute
  '/ops/clients': typeof OpsClientsIndexRoute
  '/ops/posts': typeof OpsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/calendar': typeof CalendarRoute
  '/comments': typeof CommentsRoute
  '/content': typeof ContentRoute
  '/create-content': typeof CreateContentRoute
  '/earn': typeof EarnRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRouteWithChildren
  '/post-ideas': typeof PostIdeasRoute
  '/report': typeof ReportRoute
  '/schedule': typeof ScheduleRoute
  '/trending': typeof TrendingRoute
  '/api/idea-chat': typeof ApiIdeaChatRoute
  '/ops/calendar': typeof OpsCalendarRoute
  '/ops/inbox': typeof OpsInboxRoute
  '/ops/reports': typeof OpsReportsRoute
  '/settings/target-audience': typeof SettingsTargetAudienceRoute
  '/ops/': typeof OpsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/ops/clients/$clientId': typeof OpsClientsClientIdRoute
  '/ops/posts/$postId': typeof OpsPostsPostIdRoute
  '/ops/session/$workspaceId': typeof OpsSessionWorkspaceIdRoute
  '/ops/clients/': typeof OpsClientsIndexRoute
  '/ops/posts/': typeof OpsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/brain'
    | '/calendar'
    | '/comments'
    | '/content'
    | '/create-content'
    | '/earn'
    | '/home'
    | '/inbox'
    | '/kanban'
    | '/onboarding'
    | '/ops'
    | '/post-ideas'
    | '/report'
    | '/schedule'
    | '/trending'
    | '/api/idea-chat'
    | '/ops/calendar'
    | '/ops/inbox'
    | '/ops/reports'
    | '/settings/target-audience'
    | '/ops/'
    | '/settings/'
    | '/ops/clients/$clientId'
    | '/ops/posts/$postId'
    | '/ops/session/$workspaceId'
    | '/ops/clients/'
    | '/ops/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/brain'
    | '/calendar'
    | '/comments'
    | '/content'
    | '/create-content'
    | '/earn'
    | '/home'
    | '/inbox'
    | '/kanban'
    | '/onboarding'
    | '/post-ideas'
    | '/report'
    | '/schedule'
    | '/trending'
    | '/api/idea-chat'
    | '/ops/calendar'
    | '/ops/inbox'
    | '/ops/reports'
    | '/settings/target-audience'
    | '/ops'
    | '/settings'
    | '/ops/clients/$clientId'
    | '/ops/posts/$postId'
    | '/ops/session/$workspaceId'
    | '/ops/clients'
    | '/ops/posts'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/brain'
    | '/calendar'
    | '/comments'
    | '/content'
    | '/create-content'
    | '/earn'
    | '/home'
    | '/inbox'
    | '/kanban'
    | '/onboarding'
    | '/ops'
    | '/post-ideas'
    | '/report'
    | '/schedule'
    | '/trending'
    | '/api/idea-chat'
    | '/ops/calendar'
    | '/ops/inbox'
    | '/ops/reports'
    | '/settings/target-audience'
    | '/ops/'
    | '/settings/'
    | '/ops/clients/$clientId'
    | '/ops/posts/$postId'
    | '/ops/session/$workspaceId'
    | '/ops/clients/'
    | '/ops/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BrainRoute: typeof BrainRoute
  CalendarRoute: typeof CalendarRoute
  CommentsRoute: typeof CommentsRoute
  ContentRoute: typeof ContentRoute
  CreateContentRoute: typeof CreateContentRoute
  EarnRoute: typeof EarnRoute
  HomeRoute: typeof HomeRoute
  InboxRoute: typeof InboxRoute
  KanbanRoute: typeof KanbanRoute
  OnboardingRoute: typeof OnboardingRoute
  OpsRoute: typeof OpsRouteWithChildren
  PostIdeasRoute: typeof PostIdeasRoute
  ReportRoute: typeof ReportRoute
  ScheduleRoute: typeof ScheduleRoute
  TrendingRoute: typeof TrendingRoute
  ApiIdeaChatRoute: typeof ApiIdeaChatRoute
  SettingsTargetAudienceRoute: typeof SettingsTargetAudienceRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ideas': {
      id: '/post-ideas'
      path: '/post-ideas'
      fullPath: '/post-ideas'
      preLoaderRoute: typeof PostIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-content': {
      id: '/create-content'
      path: '/create-content'
      fullPath: '/create-content'
      preLoaderRoute: typeof CreateContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/settings/target-audience': {
      id: '/settings/target-audience'
      path: '/settings/target-audience'
      fullPath: '/settings/target-audience'
      preLoaderRoute: typeof SettingsTargetAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/reports': {
      id: '/ops/reports'
      path: '/reports'
      fullPath: '/ops/reports'
      preLoaderRoute: typeof OpsReportsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/inbox': {
      id: '/ops/inbox'
      path: '/inbox'
      fullPath: '/ops/inbox'
      preLoaderRoute: typeof OpsInboxRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/calendar': {
      id: '/ops/calendar'
      path: '/calendar'
      fullPath: '/ops/calendar'
      preLoaderRoute: typeof OpsCalendarRouteImport
      parentRoute: typeof OpsRoute
    }
    '/api/idea-chat': {
      id: '/api/idea-chat'
      path: '/api/idea-chat'
      fullPath: '/api/idea-chat'
      preLoaderRoute: typeof ApiIdeaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/posts/': {
      id: '/ops/posts/'
      path: '/posts'
      fullPath: '/ops/posts/'
      preLoaderRoute: typeof OpsPostsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/clients/': {
      id: '/ops/clients/'
      path: '/clients'
      fullPath: '/ops/clients/'
      preLoaderRoute: typeof OpsClientsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/session/$workspaceId': {
      id: '/ops/session/$workspaceId'
      path: '/session/$workspaceId'
      fullPath: '/ops/session/$workspaceId'
      preLoaderRoute: typeof OpsSessionWorkspaceIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/posts/$postId': {
      id: '/ops/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/ops/posts/$postId'
      preLoaderRoute: typeof OpsPostsPostIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/clients/$clientId': {
      id: '/ops/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/ops/clients/$clientId'
      preLoaderRoute: typeof OpsClientsClientIdRouteImport
      parentRoute: typeof OpsRoute
    }
  }
}

interface OpsRouteChildren {
  OpsCalendarRoute: typeof OpsCalendarRoute
  OpsInboxRoute: typeof OpsInboxRoute
  OpsReportsRoute: typeof OpsReportsRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsClientsClientIdRoute: typeof OpsClientsClientIdRoute
  OpsPostsPostIdRoute: typeof OpsPostsPostIdRoute
  OpsSessionWorkspaceIdRoute: typeof OpsSessionWorkspaceIdRoute
  OpsClientsIndexRoute: typeof OpsClientsIndexRoute
  OpsPostsIndexRoute: typeof OpsPostsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsCalendarRoute: OpsCalendarRoute,
  OpsInboxRoute: OpsInboxRoute,
  OpsReportsRoute: OpsReportsRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsClientsClientIdRoute: OpsClientsClientIdRoute,
  OpsPostsPostIdRoute: OpsPostsPostIdRoute,
  OpsSessionWorkspaceIdRoute: OpsSessionWorkspaceIdRoute,
  OpsClientsIndexRoute: OpsClientsIndexRoute,
  OpsPostsIndexRoute: OpsPostsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  BrainRoute: BrainRoute,
  CalendarRoute: CalendarRoute,
  CommentsRoute: CommentsRoute,
  ContentRoute: ContentRoute,
  CreateContentRoute: CreateContentRoute,
  EarnRoute: EarnRoute,
  HomeRoute: HomeRoute,
  InboxRoute: InboxRoute,
  KanbanRoute: KanbanRoute,
  OnboardingRoute: OnboardingRoute,
  OpsRoute: OpsRouteWithChildren,
  PostIdeasRoute: PostIdeasRoute,
  ReportRoute: ReportRoute,
  ScheduleRoute: ScheduleRoute,
  TrendingRoute: TrendingRoute,
  ApiIdeaChatRoute: ApiIdeaChatRoute,
  SettingsTargetAudienceRoute: SettingsTargetAudienceRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
